name: CI

on:
  push:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-22.04

    container:
      image: alpine:3.19.1
      options: --user root

    steps:
      - name: Download source
        uses: actions/checkout@v4
      - name: Install dependencies of OS
        run: >
            apk add
            crystal
            shards
            libjpeg-turbo
            libjpeg-turbo-dev
            libspng
            libspng-dev
            libwebp
            libwebp-dev
            make
            openssl
            openssl-dev
            yaml
            yaml-dev
      - name: Print Crystal version
        run: crystal version
      - name: Install dependencies of project
        run: shards install
      - name: Check code style
        run: bin/ameba
      - name: Check formatting
        run: crystal tool format --check
      - name: Install MongoDB
        run: >
            echo "https://dl-cdn.alpine-linux.org/alpine/v3.19.1/main" >> sudo tee -a /etc/apk/repositories
            echo "https://dl-cdn.alpine-linux.org/alpine/v3.19.1/community" >> sudo tee -a /etc/apk/repositories
            apk add  mongodb mongodb-tools
            rc-update add mongodb default
            rc-service mongodb start
            rc-service mongodb status
      - name: Print MongoDB version
        run: mongo --version
      - name: Run tests
        run: |
          crystal spec --tag global_alias
          crystal spec --tag global_regex
          crystal spec --tag global_settings
          crystal spec --tag global_super_collection
          crystal spec --tag global_types
          crystal spec --tag i18n
          crystal spec --tag pluto
          crystal spec --tag validator
          crystal spec --tag webslug
          crystal spec --tag fields
          crystal spec --tag field_json
          crystal spec --tag model
          crystal spec --tag model_json
          crystal spec --tag mongo_client
          crystal spec --tag migration
          crystal spec --tag check
          crystal spec --tag valid
          crystal spec --tag check_required
          crystal spec --tag save_create
          crystal spec --tag save_update
          crystal spec --tag delete
          crystal spec --tag verify_password
          crystal spec --tag update_password
          crystal spec --tag unit_errors
          crystal spec --tag unit_add_del
          crystal spec --tag find_one
          crystal spec --tag find_many
          crystal spec --tag general
          crystal spec --tag indexing
          crystal spec --tag fixtures
