name: Specs

on:
  push:
  pull_request:
    branches: [main]

jobs:
  tests:
    runs-on: ubuntu-latest

    container:
      image: jrei/systemd-fedora
      options: --user root --privileged

    steps:
      - name: Update system state
        run: |
          sudo dnf update -y
          dnf install -y sudo
          sudo dnf install -y systemctl
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install graphics libraries
        run: |
          sudo dnf install -y libjpeg-turbo turbojpeg-devel
          sudo dnf install -y libspng libspng-devel
          sudo dnf install -y libwebp libwebp-devel
          sudo dnf install -y libsharpyuv.so.0
      - name: Install MongoDB
        run: |
          sudo tee /etc/yum.repos.d/mongodb.repo << "EOF" > /dev/null
          [mongodb]
          name=MongoDB Repository
          baseurl=https://repo.mongodb.org/yum/redhat/9/mongodb-org/7.0/${basearch}/
          gpgcheck=1
          enabled=1
          gpgkey=https://www.mongodb.org/static/pgp/server-7.0.asc
          EOF
      - name: Start MongoDB
        run: |
          sudo dnf install -y mongodb-org
          sudo systemctl start mongod.service
