name: Specs

on:
  push:
  pull_request:
    branches: [main]

jobs:
  tests:
    runs-on: ubuntu-latest

    container:
      image: ubuntu:latest
      options: --user root

    steps:
      - name: Update system state
        run: |
          apt update
          apt install -y sudo
          sudo apt install -y curl gnupg2 systemctl git
      - name: Install Crystal language
        run: sudo apt install -y crystal shards
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install dependencies
        run: shards install
      - name: Check code style
        run: bin/ameba
      - name: Check formatting
        run: crystal tool format --check
      - name: Install graphics libraries
        run: |
          sudo apt install -y libturbojpeg0 libturbojpeg0-dev \
            libspng0 libspng-dev libwebp-dev libsharpyuv0 libsharpyuv-dev
      - name: Install and start MongoDB
        run: |
          curl -fsSL https://www.mongodb.org/static/pgp/server-7.0.asc | \
            sudo gpg -o /usr/share/keyrings/mongodb-server-7.0.gpg --dearmor
          echo "deb [ arch=amd64,arm64 signed-by=/usr/share/keyrings/mongodb-server-7.0.gpg ] \
            https://repo.mongodb.org/apt/ubuntu jammy/mongodb-org/7.0 multiverse" | \
            sudo tee /etc/apt/sources.list.d/mongodb-org-7.0.list
          sudo apt update
          sudo apt install -y mongodb-org
          mongod --version
          sudo systemctl start mongod
      - name: Run tests
        run: |
          crystal spec --tag global_alias
          crystal spec --tag global_regex
          crystal spec --tag global_settings
          crystal spec --tag global_super_collection
          crystal spec --tag global_types
          crystal spec --tag i18n
          crystal spec --tag pluto
          crystal spec --tag validator
          crystal spec --tag webslug
          crystal spec --tag fields
          crystal spec --tag field_json
          crystal spec --tag model
          crystal spec --tag model_json
          crystal spec --tag mongo_client
          crystal spec --tag migration
          crystal spec --tag check
          crystal spec --tag valid
          crystal spec --tag check_required
          crystal spec --tag save_create
          crystal spec --tag save_update
          crystal spec --tag delete
          crystal spec --tag verify_password
          crystal spec --tag update_password
          crystal spec --tag unit_errors
          crystal spec --tag unit_add_del
          crystal spec --tag find_one
          crystal spec --tag find_many
          crystal spec --tag general
          crystal spec --tag indexing
          crystal spec --tag fixtures
